### PR TITLE
Fix catchup by refreshing the whitelist after each close

### PR DESCRIPTION
**Pull request by avi-kik**

### CODE REVIEW

**Comment by oryband** [comment]
@avi-kik  waiting for unit tests before reviewing

**Comment by avi-kik** [comment]
There will be no unit tests today.  Probably not ever.

**Comment by avi-kik** [comment]
`stellar-core` does not have any infrastructure for testing catchup, so there is no test to modify or adapt to test this fix.  It is best done as an integration test.

**Comment by oryband** [comment]
ok. we'll need to run these tests then before merging this pr

**Pull request merged**
